### ISSUE TITLE
What is this project really?

### ISSUE THREAD

**Issue by amerireza** [wso2/analytics-esb#8]
I am wondering that readme file is empty, what is it really? please let us know about this project, Thanks.

**Comment by dunithd** [comment]
Hi amerireza,
This is the source code repository for WSO2 DAS for ESB analytics product. This repository is a collection of components and features that are required to provide statistical analytics support for WSO2 ESB.

**Comment by amerireza** [comment]
Since I am new to DAS and need to start monitoring service for my working WSO2 ESB, I am curious that I need this package to run the analytics for my ESB or all packages are in the box of DAS?

**Comment by gokul** [comment]
Hi amerireza,

If your requirement is to set up analytics to your ESB, then you do not need anything apart from your original installation of ESB and this server (i.e. ESB Analytics server). 

Kindly note that this project is still being worked upon, and will only work with the current ESB under development (i.e. ESB 5.0.0-SNAPSHOT). However, you are welcome to try this out through following the steps below:

- Get a clone of the master branch of the ESB product (from https://github.com/wso2/product-esb)
- Get a clone of the current repo's master branch
- Build both through maven (i.e. mvn clean install)
- Offset either ESB or ESB Analytics Server ports and connect them through "DAS Configuration" under the ESB's "Configure" menu in the management console
- Enable statistics for your ESB artifacts of choice and the  visit the analytics server's Analytics Dashboard.

We'd be happy to answer any further questions, should you have any.

Best regards,
Gokul.

**Comment by amerireza** [comment]
Hi gokul,
Thanks for your complete and kind answer. If I had a chance to build the repo before you release it, I will get back to you with my probable comments.

Thanks,
Reza

**Comment by gokul** [comment]
Hi Reza,

We've just released the beta versions for both ESB and ESB Analytics. If you wish, you could download them from below and try them out:

ESB: https://github.com/wso2/product-esb/releases/tag/v5.0.0-BETA
ESB Analytics: https://github.com/wso2/analytics-esb/releases/tag/v1.0.0-beta

Cheers,
Gokul.
